apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 2048-game
  namespace: argocd
spec:
  destination:
    namespace: 2048-game
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://github.com/ivaylo-tsv/csggbt.git
    targetRevision: HEAD
    ref: here
    path: manifests/2048-game/
