apiVersion: batch/v1
kind: Job
metadata:
  name: install-argo-cd-crds
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - name: crd-installer
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/crds/appproject-crd.yaml
            - kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/crds/application-crd.yaml
      restartPolicy: OnFailure
