spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:ivaylo-tsv/csggbt.git
    targetRevision: HEAD
applications:
  - name: assets
  - name: carts
  - name: catalog
  - name: checkout
  - name: orders
  - name: other
  - name: rabbitmq
  - name: ui
