# name: "Master Workflow"

# on:
#     pull_request:
#       branches: ["master"]
#     push:
#       branches: ["master"]
#     workflow_dispatch:

# permissions: write-all

# jobs: 
#     bootstrap: 
#         uses: ./.github/workflows/bootstrap.yaml
#         secrets: inherit 
#     main:
#         uses: ./.github/workflows/main.yaml
#         secrets: inherit
