apiVersion: v2
name: argocd-umbrella
description: Umbrella Chart for argo-cd
version: 1.0.0
dependencies:
  - name: argo-cd
    version: 7.1.2
    repository: https://argoproj.github.io/argo-helm
    alias: argocd
    condition: argocd.enabled
