argocd:
  enabled: true 
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  crds:
    install: true
    keep: true 
  server: 
    extraArgs:
      - --insecure
  repositories:
    csggbt-repo:
      url: https://github.com/ivaylo-tsv/csggbt.git
      type: github
      name: csggbt-repo 
  configs:
    secret:
      argocdServerAdminPassword: "$2y$10$FrWT32rBLlWgECZpiokJAOCYpWDEhMNr2OqKOgHuevpPg/4eEsp5C" # csggbt-argocd-password
