argocd:
  enabled: true 
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  crds:
    install: true
    keep: true 
  server: 
    extraArgs:
      - --insecure

argocd-apps:
  enabled: true
  applications: 
    root-app:
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      project: default
      sources:
        - repoURL: https://github.com/ivaylo-tsv/csggbt.git
          targetRevision: HEAD
          path: helm/charts/root-app
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          syncOptions:
          - CreateNamespace=true
        
