argocd:
  enabled: true 
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  crds:
    install: true
    keep: true 
  server: 
    extraArgs:
      - --insecure
  repositories:
    csggbt-repo:
      url: https://github.com/ivaylo-tsv/csggbt.git
      type: github
      name: csggbt-repo 

        
