argocd:
  enabled: true 
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  crds:
    install: true
    keep: true 
  server: 
    extraArgs:
      - --insecure
  repositories:
    csggbt-repo:
      url: https://github.com/ivaylo-tsv/csggbt.git
      type: github
      name: csggbt-repo 

argocd-apps:
  enabled: true
  applications: 
    2048-game:
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      project: default
      sources:
        - repoURL: https://github.com/ivaylo-tsv/csggbt.git
          targetRevision: HEAD
          path: manifests/2048-game/
      destination:
        server: https://kubernetes.default.svc
        namespace: game-2048
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        
