apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
spec:
  project: default
  source:
    repoURL: https://github.com/ivaylo-tsv/csggbt.git
    path: helm/charts/root-app/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocdc
  syncPolicy:
    automated:
      selfHeal: true