grafana:
  enabled: true 
  # grafana.ini:
  #   server:
  #     domain: k8s-csggbt-72528fc5f8-774864793.eu-west-1.elb.amazonaws.com
  #     root_url: "%(protocol)s://%(domain)s/grafana"
  #     serve_from_sub_path: true
ingress:
  enabled: true
  hosts:
    - "k8s-csggbt-72528fc5f8-774864793.eu-west-1.elb.amazonaws.com"
  path: "/grafana"