grafana:
  enabled: true 
  # ingress:
  #   enabled: true
  #   ingressClassName: alb
  #   annotations:
  #     alb.ingress.kubernetes.io/group.name: csggbt
  #     alb.ingress.kubernetes.io/scheme: internet-facing
  #     alb.ingress.kubernetes.io/target-type: ip

    path: /grafana/

  grafana.ini:
    server:
      root_url: http://k8s-csggbt-72528fc5f8-1344277348.eu-west-1.elb.amazonaws.com/grafana